name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server117.hosting.reg.ru
          username: u2272489_ruslan
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          server-dir: /www/newdev.site/wp-content/themes/newtheme/
